# Allow the provisioner to read any secret in the cluster

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: smb-csi-provisioner-configmap-and-secret-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-csi-provisioner-configmap-and-secret-reader-role
subjects:
- kind: ServiceAccount
  name: smb-csi-driver-controller-sa
  namespace: openshift-cluster-csi-drivers
